<main id="loadingMain">
  <div class="loadingio-spinner-double-ring-x9nfhyuowp"><div class="ldio-nw9hvjj2q4">
    <div></div>
    <div></div>
    <div><div></div></div>
    <div><div></div></div>
    </div></div>
</main>
<style type="text/css" scoped>
@keyframes ldio-nw9hvjj2q4 {
  0% { transform: rotate(0) }
  100% { transform: rotate(360deg) }
}
#loadingMain {
  z-index: 2;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  position: absolute;
  display: flex;
  justify-content: center;
  align-items: center;
  background-color: rgba(112, 112, 112, 0.7);
}
.ldio-nw9hvjj2q4 div { box-sizing: border-box!important }
.ldio-nw9hvjj2q4 > div {
  position: absolute;
  width: 82.8px;
  height: 82.8px;
  top: 18.599999999999998px;
  left: 18.599999999999998px;
  border-radius: 50%;
  border: 6px solid #000;
  border-color: #ee5a30 transparent #ee5a30 transparent;
  animation: ldio-nw9hvjj2q4 0.6666666666666666s linear infinite;
}

.ldio-nw9hvjj2q4 > div:nth-child(2), .ldio-nw9hvjj2q4 > div:nth-child(4) {
  width: 68.39999999999999px;
  height: 68.39999999999999px;
  top: 25.8px;
  left: 25.8px;
  animation: ldio-nw9hvjj2q4 0.6666666666666666s linear infinite reverse;
}
.ldio-nw9hvjj2q4 > div:nth-child(2) {
  border-color: transparent #ffffff transparent #ffffff
}
.ldio-nw9hvjj2q4 > div:nth-child(3) { border-color: transparent }
.ldio-nw9hvjj2q4 > div:nth-child(3) div {
  position: absolute;
  width: 100%;
  height: 100%;
  transform: rotate(45deg);
}
.ldio-nw9hvjj2q4 > div:nth-child(3) div:before, .ldio-nw9hvjj2q4 > div:nth-child(3) div:after { 
  content: "";
  display: block;
  position: absolute;
  width: 6px;
  height: 6px;
  top: -6px;
  left: 32.4px;
  background: #ee5a30;
  border-radius: 50%;
  box-shadow: 0 76.8px 0 0 #ee5a30;
}
.ldio-nw9hvjj2q4 > div:nth-child(3) div:after {
  left: -6px;
  top: 32.4px;
  box-shadow: 76.8px 0 0 0 #ee5a30;
}

.ldio-nw9hvjj2q4 > div:nth-child(4) { border-color: transparent; }
.ldio-nw9hvjj2q4 > div:nth-child(4) div {
  position: absolute;
  width: 100%;
  height: 100%;
  transform: rotate(45deg);
}
.ldio-nw9hvjj2q4 > div:nth-child(4) div:before, .ldio-nw9hvjj2q4 > div:nth-child(4) div:after {
  content: "";
  display: block;
  position: absolute;
  width: 6px;
  height: 6px;
  top: -6px;
  left: 25.2px;
  background: #ffffff;
  border-radius: 50%;
  box-shadow: 0 62.4px 0 0 #ffffff;
}
.ldio-nw9hvjj2q4 > div:nth-child(4) div:after {
  left: -6px;
  top: 25.2px;
  box-shadow: 62.4px 0 0 0 #ffffff;
}
.loadingio-spinner-double-ring-x9nfhyuowp {
  width: 120px;
  height: 120px;
  display: inline-block;
  overflow: hidden;
}
.ldio-nw9hvjj2q4 {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-nw9hvjj2q4 div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>